version: '3.1'

services:
  demo_apache:
    build:
        context: .
        dockerfile: Dockerfile
    restart: always
    # depends_on:
    #   - mysql_db
    ports:
      - 8888:80
      - 8444:443
    volumes:
      - ./src:/var/www/html
      # - ./var_datas:/var/data/demo_apache
